# databases:
#   - name: postgres
#     ipAllowList: []

# services:
#   - type: web
#     name: budgetapp
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: postgres
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
#   - type: redis
#     name: redis
#     ipAllowList: []
#     plan: free
#     maxmemoryPolicy: noeviction

databases:
  - name: my-database
    databaseName: capston_database_gbky_ghi4
    user: ogiogiovictor

services:
  - type: web
    name: my-database
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        plan: free

